"""first migrate

Revision ID: 18acfedcbf99
Revises: 586d674db2bc
Create Date: 2024-02-19 00:04:04.517762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18acfedcbf99'
down_revision = '586d674db2bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('botanical_owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forest_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('tender_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'forest_owner', ['forest_id'], ['owner_id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tender_user_id_fkey', 'user', ['user_id'], ['user_id'])
        batch_op.drop_column('forest_id')

    with op.batch_alter_table('botanical_owner', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('owner_name')

    # ### end Alembic commands ###
