"""first migrate

Revision ID: 586d674db2bc
Revises: 
Create Date: 2024-02-18 23:47:51.714833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586d674db2bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('Forest Owner', 'Botanical Owner', name='user_roles'), nullable=False),
    sa.Column('subscription_type', sa.Enum('Free', 'Premium', name='subscription_types'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('forest_owner',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('forest',
    sa.Column('forest_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('forest_name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('soil_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['forest_owner.owner_id'], ),
    sa.PrimaryKeyConstraint('forest_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forest')
    op.drop_table('forest_owner')
    op.drop_table('user')
    # ### end Alembic commands ###
